import "@/styles/globals.css";
import type { Metadata } from "next";
import { cn } from "@/libs/class-names";
import { fontVariables } from "@/libs/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html className="scroll-smooth" lang="en">
      <body
        className={cn(
          "overscroll-none bg-base font-sans text-text antialiased",
          fontVariables
        )}
      >
        {children}
      </body>
    </html>
  );
}
