import type { Metadata } from 'next'
import { cn } from '@/lib/class-names'
import { fontVariables } from '@/lib/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn(fontVariables, 'overscroll-none bg-background font-body text-foreground antialiased')}>
        {children}
      </body>
    </html>
  )
}
